PREFIX bif: <bif:>
PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>
INSERT {
  []
    a sd:ServiceDescription ;
    eg:dbmsId   ?dbmsId ;
    eg:dbmsName ?dbmsName ;
    eg:dbmsVersion ?dbmsVersion
}
WHERE {
  OPTIONAL {
  SERVICE SILENT <env://REMOTE> {
    BIND( bif:sys_stat('st_dbms_name')          AS ?dbmsRawName)
    BIND( bif:sys_stat('st_dbms_ver')           AS ?dbmsVersion)
      # ( bif:sys_stat('st_dbms_name')          AS ?dbmsName )
      # ( bif:sys_stat('st_dbms_ver')           AS ?dbmsVersion )
      # ( bif:sys_stat('st_build_thread_model') AS ?thread )
      # ( bif:sys_stat('st_build_opsys_id')     AS ?opsys )
      # ( bif:sys_stat('st_build_date')         AS ?date )
      # ( bif:sys_stat('st_lic_owner')          AS ?owner )
      # ( bif:sys_stat('st_lic_serial_number')  AS ?serial )
      # WHERE
      #   {  ?s a ?o  }
      # LIMIT 1
  }
  }
  OPTIONAL {
    SERVICE SILENT <env://REMOTE> {
      ?dbmsRawName apf:versionARQ ?dbmsVersion
    }
  }
  BIND( REPLACE(REPLACE(STR(?dbmsRawName), '\\s+', ' '), ' ', '-') AS ?dbmsName)
  BIND(CONCAT(?dbmsName, ':', STR(?dbmsVersion)) AS ?dbmsId)
}

