version: '3.1'

services:
  db:
    image: nawer/blazegraph
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    volumes:
      #- /var/blazegraph:/var/lib/blazegraph
      - ./data:/var/blazegraph
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    network_mode: host
    ports:
      - "9999:9999"

