version: '3.1'

services:
  db:
    image: ontotext/graphdb:8.9.0-se
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    volumes:
      - ./data:/opt/graphdb/home
    ports:
      - "7200:7200"

